### ISSUE TITLE
Ajout de nouveau projet : retourne une erreur, et la page ne se rafraichit pas

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#28]
Lorsque que j'ajoute un nouveau projet (bien formé), un message apparait : "Erreur lors de la communication avec le serveur !".
Cependant, après avoir rafraichi la page, le projet apparait dans le bandeau 'Select project'. 

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Function.m.parseJSON (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/jquery/jquery.js:4:15739 [^])
    at http://localhost:8080/ProtegeWeb4SEAMLESS/controllers/projects.js:49:22 [^]
    at Scope.$eval (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/angularjs/all.js:14547:28 [^])
    at Scope.$apply (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/angularjs/all.js:14646:23 [^])
    at Object.$.ajaxForm.complete (http://localhost:8080/ProtegeWeb4SEAMLESS/controllers/projects.js:48:11 [^])
    at Object.t.complete (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/jquery/ajax.form.js:11:10177 [^])
    at j (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/jquery/jquery.js:2:27244 [^])
    at Object.k.fireWith (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/jquery/jquery.js:2:28057 [^])
    at x (http://localhost:8080/ProtegeWeb4SEAMLESS/vendors/jquery/jquery.js:4:21971 [^])

**Comment by WebMSB** [comment]
suite à la résolution du ticket https://github.com/webNeat/pwfs/issues/11 ce ticket est résolu
